version: '3.5'
services:
  php8:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/opt/project
    command: "${XDEBUG_USER_CONFIG:--d xdebug.discover_client_host=true}"
    environment:
      PHP_IDE_CONFIG: "serverName=AOC"
    working_dir: /opt/project
